"""change picture url to profile url of user model

Revision ID: a32024aba2c7
Revises: 057b7a3cf270
Create Date: 2026-04-10 20:07:42.729834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a32024aba2c7'
down_revision: Union[str, Sequence[str], None] = '057b7a3cf270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_url')
    # ### end Alembic commands ###
